### ISSUE TITLE
cannot train on voc.  training get stuck.

### ISSUE THREAD

**Issue by bloatybo** [sufeidechabei/gluon-mobilenet-yolov3#4]
I have 4 GTX 1080 ti card, runing cuda 9.0 cudnn 7.0. Python 3.6.7 on Ubuntu 16.04.5 LTS.
tried both mxnet 1.3.1 gluoncv 0.3.0; mxnet 1.5.0 gluoncv 0.4.0.
training command:
python3 train_yolo3_mobilenet.py --network mobilenet1_0 --dataset voc --gpus 0,1,2,3 --batch-size 32 -j 8 --log-interval 2 --lr-decay-epoch 160,180 --epochs 200 --syncbn --warmup-epochs 4

log:
INFO:root:Namespace(batch_size=32, data_shape=416, dataset='voc', epochs=200, gpus='0,1,2,3', label_smooth=False, log_interval=2, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,180', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='mobilenet1_0', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=16551, num_workers=8, resume='', save_interval=10, save_prefix='yolo3_mobilenet1_0_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, warmup_epochs=4, warmup_lr=0.0, wd=0.0005)
INFO:root:Start training from [Epoch 0]

and it stucks here forever.

all get stuck at this line:
line 392:   obj_metrics.update(0, obj_losses)

gpu usage is at 0% cpu usage is also low around %0.7-0.3%:
![image](https://user-images.githubusercontent.com/10253181/51132418-fe6d3e80-17e6-11e9-8e02-817b42ffa5d6.png)

also tried not using syncbn. nothing changes.

**Comment by sufeidechabei** [comment]
can you show more details about the error?

**Comment by sufeidechabei** [comment]
you can reduce the batchsize,  then run the code again.
